# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('latency_min', models.IntegerField()),
                ('latency_av', models.IntegerField()),
                ('latency_max', models.IntegerField()),
                ('traffic_rx', models.IntegerField()),
                ('traffic_tx', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='bandwidth',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaisp.Line'),
        ),
    ]
